apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nodejs/node-app:latest  # Replace with your actual image details
        ports:
        - containerPort: 3000  # Replace with the port your Node.js app is listening on
        env:
        - name: NODE_ENV
          value: production  # Set your desired environment variables
